### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by howard84527** [jackd/template_ffd#10]
Hi,
Sorry to bother you, I got an error while running the "python render_cat.py plane" 
I have downloaded the ShapeNet Core dataset and exported the path

Here is the detailed description of the error.

Rendering 4045 images for cat 02691156
 |                                | 1/4045
2018-07-13 11:24:01.861504
Rendering 8504e370736b26604d210d9468aedaf2
Traceback (most recent call last):
  File "render_cat.py", line 106, in <module>
    args.example_ids, args.fixed_meshes, args.blender_path)
  File "render_cat.py", line 86, in render_cat
    overwrite, call_kwargs, blender_path=blender_path)
  File "render_cat.py", line 60, in render_example
    config, obj_path, cat_dir, call_kwargs, blender_path=blender_path)
  File "render_cat.py", line 31, in render_obj
    ], **call_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by jackd** [comment]
Do you have the blender executable on your path? To test: `blender -v` from the scripts directory.

**Comment by howard84527** [comment]
I solved the problem.
Thank you for your help.
