### ISSUE TITLE
InvalidArgumentError: 1-th value returned by pyfunc_1 is double, but expects float

### ISSUE THREAD

**Issue by xiaomingjie** [jackd/template_ffd#2]
Hi @jackd,
See you again here XD..
when trying to train the network, the issue occured. 

```
2018-05-16 12:25:02.195364: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: 1-th value returned by pyfunc_1 is double, but expects float
	 [[Node: PyFuncStateless = PyFuncStateless[Tin=[DT_STRING], Tout=[DT_UINT8, DT_FLOAT], token="pyfunc_1"](arg0)]]
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    train(args.model_id, max_steps=args.max_steps)
  File "train.py", line 8, in train
    builder.train(max_steps=max_steps)
  File "/media/tree/data1/projects/data_prepare/template_ffd/model/builder.py", line 242, in train
    estimator.train(self.get_train_inputs, **train_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 783, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 1-th value returned by pyfunc_1 is double, but expects float
	 [[Node: PyFuncStateless = PyFuncStateless[Tin=[DT_STRING], Tout=[DT_UINT8, DT_FLOAT], token="pyfunc_1"](arg0)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?], [?,192,256,3], [?,1024,3]], output_types=[DT_STRING, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
	 [[Node: IteratorGetNext/_2101 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_193_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```
It seems like input shape went wrong and it didn't get the batch size?Or my setting went wrong?

I am running at

> Ubuntu16.04
> Python2.7
> TensorFlow1.4

And for more private request, could you release an example to load your dataset and finally get input tensor to tensorflow? 

Thanks for your amazing job and looking forward to your reply!

**Comment by jackd** [comment]
Hi Sean, the issue is with the dtype (float64, where as my tf implementation is expecting a float32). I'm a little surprised by this, since I thought my `shapenet` repo produced clouds that are float32, but I suppose I shouldn't make that assumption. I've just [pushed](https://github.com/jackd/template_ffd/commit/c176094a6c99a225a16a7c7c0ed418df0e213116) something that'll hopefully fix that.

If that doesn't work, please include the contents of your model's params file and I'll look into it further.

Alas I don't own the shapenet data so I can't provide it directly - the best I can do is provide the manipulation/preprocessing in `shapenet`. Tensorflow processing is done in [`model/template_ffd_builder`](https://github.com/jackd/template_ffd/blob/master/model/template_ffd_builder.py)'s `get_dataset` function.

I'd suggest you get the input pipeline up and running first with `vis_inputs` and only try `train`ing a model once you're sure that's working.

**Comment by xiaomingjie** [comment]
It works!

Actually I have used your rendering and sampling method to get the dataset I want, just don't know how to use the dataset. BTW, rendering images really took time especially when I reached 30th or 40th category.. As you say, I am going to look into template_ffd_builder to see how I can deal with data.

What's more, your work in this paper is really outstanding since you got results which nearly promoted the performance to another level and it's like 4 times better than PSGN..
It really hurts me since I nearly have no space to improve that....Just kidding lol.
Maybe I will have more questions about your paper or work, hope you won't be bored with me..

However, congratulations and thanks for your help!

**Comment by jackd** [comment]
[`dids`](https://github.com/jackd/dids) is getting a little bit more complicated that I originally intended (I need a better way to handle autosaving datasets...) but I'd encourage you to have a look through the [examples](https://github.com/jackd/dids/tree/master/example) if you haven't already. There's a lot of functionality I've added over time, but understanding the core methods - `subset`, `map`, `Dataset.zip` - will probably get you a fair way.
